"""empty message

Revision ID: 6639cdc6c690
Revises: 1b451c2b44a1
Create Date: 2023-04-03 22:26:44.208399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6639cdc6c690'
down_revision = '1b451c2b44a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
